### ISSUE TITLE
Debugger prints wrong sort information

### ISSUE THREAD

**Issue by radumereuta** [kframework/llvm-backend#272]
The LLVM runtime debugger doesn't handle sort information that well, so parametric productions like `#token` or `inj` may have incorrect sorts:

```
#token("Pgm","Id") // should have been KSort instead of Id
```
```
inj{KoreDefinition{}, KItem{}} // should have been SortDeclaration instead of KItem
```
Apparently is not that easy to fix, so my first suggestion was to just say `missing information` where the sort information is not 100% sure, but that's not that easy either.

**Comment by dwightguth** [comment]
Essentially what needs to happen here is we need to maintain a table in static memory that maps from symbol and argument position to the sort of the child, and look up in that table when pretty printing terms in order to determine the sort of the child (we already do this when pretty printing outside the debugger, but it needs to be refactored into a static table in memory). Then we need to use that sort to adjust the sort of injections and tokens, which are not fully specified otherwise.
